# EPR Analysis of the Full Chip

A Step-by-Step Superconducting Quantum Chip Design Tutorial: from Theory to Simulation

Tutorial Videos: https://www.youtube.com/playlist?list=PLnK6MrIqGXsJF6XLP-1jIBBhsCS5ZQSmR

James Saslow, Shreyan Juvvadi, Hiu Yung Wong*

contact: Hiu-Yung Wong, hiuyung.wong@sjsu.edu

In [1]:
# Importing Packages
import pyEPR as epr
from qiskit_metal import MetalGUI, Dict, open_docs

C:\Users\012738063\AppData\Local\anaconda3\envs\qmetal3\Lib\site-packages\qutip\__init__.py:71: UserWarning: Runtime cython compilation does not work on Python 3.12.
  warnings.warn(

In [2]:
# Specifying path on my local machine, ansys project name, and design name within the ansys project

path = "C:\\Users\\012738063\\Documents\\Ansoft"
project_name = "Project28" 
design_name = "Full_Chip_Eigenmode"

In [26]:
# Opening the project in ansys
pinfo = epr.ProjectInfo(project_path = path,
                        project_name = project_name,
                        design_name  = design_name)

INFO 05:23PM [connect_project]: Connecting to Ansys Desktop API...
INFO 05:23PM [load_ansys_project]: 	File path to HFSS project found.
INFO 05:23PM [load_ansys_project]: 	Opened Ansys App
INFO 05:23PM [load_ansys_project]: 	Opened Ansys Desktop v2026.1.2
INFO 05:23PM [load_ansys_project]: 	Opened Ansys Project
	Folder:    C:/Users/012738063/Documents/Ansoft/
	Project:   Project28
INFO 05:23PM [connect_design]: 	Opened active design
	Design:    Full_Chip_Eigenmode [Solution type: Eigenmode]
INFO 05:23PM [get_setup]: 	Opened setup `Setup`  (<class 'pyEPR.ansys.HfssEMSetup'>)
INFO 05:23PM [connect]: 	Connected to project "Project28" and design "Full_Chip_Eigenmode" 😀

In [27]:
# Printing Object Names in ansys design
pinfo.get_all_object_names()

['main',
 'sample_holder',
 'prime_cpw_TQ1',
 'second_cpw_TQ1',
 'prime_cpw_TQ0',
 'second_cpw_TQ0',
 'prime_cpw_TQ3',
 'second_cpw_TQ3',
 'trace_cpw_left',
 'trace_cpw_right',
 'b_wire_Q0_bottom',
 'second_cpw_L_brackeb0_bottom',
 'trace_meander_Q0_bottom',
 'trace_bias0_bottom',
 'a_wire_Q0_top',
 'b_wire_Q0_top',
 'second_cpw_L_bracket0_top',
 'trace_bias0_top',
 'a_wire_Q1_top',
 'b_wire_Q1_top',
 'second_cpw_L_bracket1_top',
 'trace_bias1_top',
 'trace_meander_Q0_top',
 'trace_meander_Q1_top',
 'trace_two_qubit_coupler',
 'launch_pad_Transmission_Launch_Pad_L',
 'launch_pad_Transmission_Launch_Pad_R',
 'launch_pad_Qubit_0_Top_Control_Launch_Pad',
 'launch_pad_Qubit_1_Top_Control_Launch_Pad',
 'pad_top_Q0_bottom',
 'b_connector_pad_Q0_bottom',
 'launch_pad_Launch_Pad_0_Bottom',
 'pad_top_Q0_top',
 'a_connector_pad_Q0_top',
 'b_connector_pad_Q0_top',
 'pad_top_Q1_top',
 'a_connector_pad_Q1_top',
 'b_connector_pad_Q1_top',
 'JJ_rect_Lj_Q0_bottom_rect_jj_L',
 'JJ_rect_Lj_Q0_top_rect_jj_L',
 'JJ_rect_Lj_Q1_top_rect_jj_L',
 'ground_main_plane',
 'Rectangle1',
 'Rectangle2',
 'Rectangle3',
 'Rectangle4',
 'Rectangle5',
 'JJ_Lj_Q0_bottom_rect_jj_L_',
 'JJ_Lj_Q0_top_rect_jj_L_',
 'JJ_Lj_Q1_top_rect_jj_L_']

In [28]:
pinfo.design.get_setup_names()

('Setup',)

# Convert 2 JJ to 1 JJ, remember to double Cj. Reduce Lj by half.

In [29]:
# Defining the Junction in pyEPR
pinfo.junctions['j1'] = {'Lj_variable' : 'Q0_bottom_Lj',        # Inductance Variable Name
                         'rect'        : 'JJ_rect_Lj_Q0_bottom_rect_jj_L',  # Name of the rectangle geometry where Lumped RLC is specified
                         'line'        : 'JJ_Lj_Q0_bottom_rect_jj_L_',   # HFSS Polyline that spans the length of the rectangle
                         'length'      : epr.parse_units('0.06mm'),
                         'Cj_variable' : 'Q0_bottom_Cj'}  
pinfo.junctions['j2'] = {'Lj_variable' : 'Q0_top_Lj',        # Inductance Variable Name
                         'rect'        : 'JJ_rect_Lj_Q0_top_rect_jj_L',  # Name of the rectangle geometry where Lumped RLC is specified
                         'line'        : 'JJ_Lj_Q0_top_rect_jj_L_',   # HFSS Polyline that spans the length of the rectangle
                         'length'      : epr.parse_units('0.06mm'),
                         'Cj_variable' : 'Q0_top_Cj'}  

pinfo.junctions['j3'] = {'Lj_variable' : 'Q1_top_Lj',        # Inductance Variable Name
                         'rect'        : 'JJ_rect_Lj_Q1_top_rect_jj_L',  # Name of the rectangle geometry where Lumped RLC is specified
                         'line'        : 'JJ_Lj_Q1_top_rect_jj_L_',   # HFSS Polyline that spans the length of the rectangle
                         'length'      : epr.parse_units('0.06mm'),
                         'Cj_variable' : 'Q1_top_Cj'}  
pinfo.validate_junction_info()  # Raises an error if something is wrong with junction definition

In [30]:
# # Simulation Parameters

pinfo.setup.min_pass = 6
pinfo.setup.passes = 15    # Maximum Number of passes
pinfo.setup.n_modes = 9     # Specifying number of modes for eigenmode analysis
pinfo.setup.delta_f = 1
pinfo.setup.min_freq = '1.0GHz'

### Run Eigenmode Simulations

In [9]:
pinfo.setup.analyze()

INFO 04:06PM [analyze]: Analyzing setup Setup

0

In [9]:
# pinfo.design.optimetrics.solve_setup(pinfo.design.optimetrics.get_setup_names())

# Eigenmode Analysis

In [31]:
eprh = epr.DistributedAnalysis(pinfo) # epr hfss analysis

Design "Full_Chip_Eigenmode" info:
	# eigenmodes    9
	# variations    1

In [32]:
eprh.get_ansys_frequencies_all()

                Freq. (GHz)  Quality Factor
variation mode
0         0        4.322472    6.886797e+06
          1        4.765911    2.760330e+03
          2        5.414840    2.437974e+07
          3        5.699624    9.488999e+04
          4        6.085195    9.696649e+04
          5        6.822444    7.649275e+03
          6        7.332031    5.782970e+03
          7        7.516201    4.931542e+03
          8       10.311452    1.072848e+03

In [33]:
eprh.hfss_report_full_convergence()

INFO 05:23PM [__del__]: Disconnected from Ansys HFSS
INFO 05:23PM [hfss_report_full_convergence]: Creating report for variation 0
INFO 05:23PM [hfss_report_f_convergence]: Saved convergences to C:\data-pyEPR\Project28\Full_Chip_Eigenmode\hfss_eig_f_convergence.csv
INFO 05:23PM [__del__]: Disconnected from Ansys HFSS

In [34]:
eprh.get_mesh_statistics()

,Unnamed: 0,Num Tets,Min edge length,Max edge length,RMS edge length,Min tet vol,Max tet vol,Mean tet vol,Std Devn (vol)
0,main,159947,0.003167,1.064910,0.101511,7.564800e-10,0.055894,0.000094,0.000857
1,sample_holder,89813,0.003642,0.988463,0.150509,1.878870e-09,0.063061,0.000399,0.002569

# EPR Analysis

In [35]:
my_epr = eprh.do_EPR_analysis()

Variation 0  [1/1]

  Mode 0 at 4.32 GHz   [1/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               98.9%  1.419e-23 1.555e-25

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign s_0j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 98.32%
	j1               1.06013  (+)        0.0181414
		Energy fraction (Lj over Lj&Cj)= 99.12%
	j2              1.95497e-06  (+)        1.73328e-08
		Energy fraction (Lj over Lj&Cj)= 99.00%
	j3              2.5187e-06  (+)        2.55262e-08
		(U_tot_cap-U_tot_ind)/mean=-2.53%

  Mode 1 at 4.77 GHz   [2/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                3.0%  1.622e-23 1.573e-23

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_1j   sign s_1j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 97.96%
	j1              0.000388266  (+)        8.07735e-06
		Energy fraction (Lj over Lj&Cj)= 98.93%
	j2              0.0118846  (+)        0.000128098
		Energy fraction (Lj over Lj&Cj)= 98.78%
	j3              0.0192843  (+)        0.000237598
		(U_tot_cap-U_tot_ind)/mean=-0.05%

  Mode 2 at 5.41 GHz   [3/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                1.8%  2.856e-24 2.805e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_2j   sign s_2j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 97.38%
	j1              4.62831e-09  (+)        1.24291e-10
		Energy fraction (Lj over Lj&Cj)= 98.63%
	j2              0.0033662  (+)        4.68356e-05
		Energy fraction (Lj over Lj&Cj)= 98.43%
	j3              0.0152974  (+)        0.000243296
		(U_tot_cap-U_tot_ind)/mean=-0.04%

  Mode 3 at 5.70 GHz   [4/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               93.6%  6.525e-24 4.158e-25

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_3j   sign s_3j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 97.11%
	j1              1.66479e-06  (+)        4.95335e-08
		Energy fraction (Lj over Lj&Cj)= 98.48%
	j2              0.00497321  (+)        7.66644e-05
		Energy fraction (Lj over Lj&Cj)= 98.27%
	j3               1.00042  (+)        0.0176288
		(U_tot_cap-U_tot_ind)/mean=-2.46%

  Mode 4 at 6.09 GHz   [5/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               94.8%  5.295e-24 2.776e-25

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_4j   sign s_4j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 96.72%
	j1              4.83778e-07  (+)        1.64075e-08
		Energy fraction (Lj over Lj&Cj)= 98.27%
	j2               1.01378  (+)        0.0178138
		Energy fraction (Lj over Lj&Cj)= 98.03%
	j3              0.00400933  (+)        8.05317e-05
		(U_tot_cap-U_tot_ind)/mean=-2.51%

  Mode 5 at 6.82 GHz   [6/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                0.2%  1.973e-24 1.969e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_5j   sign s_5j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 95.91%
	j1              0.00227992  (+)        9.71956e-05
		Energy fraction (Lj over Lj&Cj)= 97.84%
	j2              7.56213e-09  (+)        1.67028e-10
		Energy fraction (Lj over Lj&Cj)= 97.54%
	j3              3.28156e-07  (+)        8.28527e-09
		(U_tot_cap-U_tot_ind)/mean=-0.01%

  Mode 6 at 7.33 GHz   [7/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                0.7%  1.589e-24 1.578e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_6j   sign s_6j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 95.31%
	j1              2.77053e-08  (+)        1.36414e-09
		Energy fraction (Lj over Lj&Cj)= 97.51%
	j2              5.59724e-05  (+)        1.42786e-06
		Energy fraction (Lj over Lj&Cj)= 97.17%
	j3              0.00790403  (+)        0.000230486
		(U_tot_cap-U_tot_ind)/mean=-0.03%

  Mode 7 at 7.52 GHz   [8/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                1.0%  1.112e-24   1.1e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_7j   sign s_7j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 95.08%
	j1              1.10981e-08  (+)        5.74238e-10
		Energy fraction (Lj over Lj&Cj)= 97.39%
	j2              0.0117135  (+)        0.000314012
		Energy fraction (Lj over Lj&Cj)= 97.03%
	j3              2.64121e-05  (+)        8.09367e-07
		(U_tot_cap-U_tot_ind)/mean=-0.05%

  Mode 8 at 10.31 GHz   [9/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                0.6%  1.099e-23 1.092e-23

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_8j   sign s_8j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 91.13%
	j1              9.13796e-06  (+)        8.89891e-07
		Energy fraction (Lj over Lj&Cj)= 95.20%
	j2              0.00444643  (+)        0.000224344
		Energy fraction (Lj over Lj&Cj)= 94.55%
	j3              0.00361453  (+)        0.000208467
		(U_tot_cap-U_tot_ind)/mean=-0.06%

ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project28\Full_Chip_Eigenmode\2026-08-05 17-23-44.npz

# Cross Kerr Calculation

In [36]:
epra = epr.QuantumAnalysis(eprh.data_filename)

WARNING 05:29PM [__init__]: <p>Error: <class 'IndexError'></p>

	 Differences in variations:

In [37]:
sol = epra.analyze_all_variations(cos_trunc = None, fock_trunc = 6)

WARNING:py.warnings:C:\Users\012738063\AppData\Local\anaconda3\envs\qmetal3\Lib\site-packages\pyEPR\core_quantum_analysis.py:692: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  result['f_ND'] = pd.Series(f1_ND)*1E-6  # MHz

WARNING:py.warnings:C:\Users\012738063\AppData\Local\anaconda3\envs\qmetal3\Lib\site-packages\pyEPR\core_quantum_analysis.py:711: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  result['Q_coupling'] = self.Qm_coupling[variation][self.Qm_coupling[variation].columns[junctions]][modes]#TODO change the columns to junctions

WARNING:py.warnings:C:\Users\012738063\AppData\Local\anaconda3\envs\qmetal3\Lib\site-packages\pyEPR\core_quantum_analysis.py:716: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  result['Qs'] = self.Qs[variation][self.PM[variation].columns[junctions]][modes] #TODO change the columns to junctions

 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Variation 0

Pm_norm=
modes
0    0.950313
1    0.982521
2    0.977096
3    0.950420
4    0.949882
5    0.936530
6    0.956758
7    0.959956
8    0.919165
dtype: float64

Pm_norm idx =
      j1     j2     j3
0   True  False  False
1  False  False  False
2  False  False  False
3  False  False   True
4  False   True  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
*** P (participation matrix, not normlz.)
             j1            j2            j3
0  1.041237e+00  1.920137e-06  2.473817e-06
1  3.881207e-04  1.188018e-02  1.927713e-02
2  4.626964e-09  3.365227e-03  1.529293e-02
3  1.635824e-06  4.886693e-03  9.830197e-01
4  4.752729e-07  9.959582e-01  3.938844e-03
5  2.279695e-03  7.561391e-09  3.281241e-07
6  2.769888e-08  5.595941e-05  7.902198e-03
7  1.109458e-08  1.170979e-02  2.640376e-05
8  9.134001e-06  4.444500e-03  3.612964e-03

*** S (sign-bit matrix)
   s_j1  s_j2  s_j3
0     1    -1    -1
1    -1    -1    -1
2    -1    -1     1
3     1     1    -1
4     1    -1    -1
5     1     1    -1
6     1    -1    -1
7    -1     1     1
8     1    -1     1
*** P (participation matrix, normalized.)
      0.99  1.9e-06  2.5e-06
   0.00039    0.012    0.019
   4.6e-09   0.0034    0.015
   1.6e-06   0.0049     0.93
   4.8e-07     0.95   0.0039
    0.0023  7.6e-09  3.3e-07
   2.8e-08  5.6e-05   0.0079
   1.1e-08    0.012  2.6e-05
   9.1e-06   0.0044   0.0036

*** Chi matrix O1 PT (MHz)
    Diag is anharmonicity, off diag is full cross-Kerr.
       162     0.14 1.26e-05  0.00131 0.000661     1.18  2.2e-05 1.31e-05  0.00715
      0.14   0.0591   0.0894     5.15     3.02 0.000513   0.0561    0.046   0.0598
  1.26e-05   0.0894   0.0376     4.64    0.985 1.96e-06   0.0505   0.0149   0.0401
   0.00131     5.15     4.64      149     2.81 0.000128     3.24   0.0336      2.1
  0.000661     3.02    0.985     2.81      152 4.09e-06   0.0363     4.66     2.43
      1.18 0.000513 1.96e-06 0.000128 4.09e-06  0.00215 1.42e-06 6.94e-08 2.69e-05
   2.2e-05   0.0561   0.0505     3.24   0.0363 1.42e-06   0.0176 0.000453   0.0229
  1.31e-05    0.046   0.0149   0.0336     4.66 6.94e-08 0.000453   0.0356   0.0372
   0.00715   0.0598   0.0401      2.1     2.43 2.69e-05   0.0229   0.0372   0.0169

*** Chi matrix ND (MHz)

*** Frequencies O1 PT (MHz)
0     4159.533257
1     4761.568811
2     5411.893136
3     5541.659719
4     5925.904086
5     6821.850981
6     7330.309369
7     7513.770313
8    10309.086006
dtype: float64

*** Frequencies ND (MHz)
Series([], dtype: float64)

*** Q_coupling
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
''' After disconnecting, you can close Ansys in the external window '''
pinfo.disconnect()