# EPR Analysis of the Full Chip

A Step-by-Step Superconducting Quantum Chip Design Tutorial: from Theory to Simulation

Tutorial Videos: https://www.youtube.com/playlist?list=PLnK6MrIqGXsJF6XLP-1jIBBhsCS5ZQSmR

James Saslow, Shreyan Juvvadi, Hiu Yung Wong*

contact: Hiu-Yung Wong, hiuyung.wong@sjsu.edu

In [1]:
# Importing Packages
import pyEPR as epr
from qiskit_metal import MetalGUI, Dict, open_docs

C:\Users\012738063\AppData\Local\anaconda3\envs\qmetal3\Lib\site-packages\qutip\__init__.py:71: UserWarning: Runtime cython compilation does not work on Python 3.12.
  warnings.warn(

In [2]:
# Specifying path on my local machine, ansys project name, and design name within the ansys project

path = "C:\\Users\\012738063\\Documents\\Ansoft"
project_name = "Project28" 
design_name = "Full_Chip_Eigenmode"

In [3]:
# Opening the project in ansys
pinfo = epr.ProjectInfo(project_path = path,
                        project_name = project_name,
                        design_name  = design_name)

INFO 04:03PM [connect_project]: Connecting to Ansys Desktop API...
INFO 04:03PM [load_ansys_project]: 	File path to HFSS project found.
INFO 04:03PM [load_ansys_project]: 	Opened Ansys App
INFO 04:03PM [load_ansys_project]: 	Opened Ansys Desktop v2026.1.2
INFO 04:03PM [load_ansys_project]: 	Opened Ansys Project
	Folder:    C:/Users/012738063/Documents/Ansoft/
	Project:   Project28
INFO 04:03PM [connect_design]: 	Opened active design
	Design:    Full_Chip_Eigenmode [Solution type: Eigenmode]
INFO 04:03PM [get_setup]: 	Opened setup `Setup`  (<class 'pyEPR.ansys.HfssEMSetup'>)
INFO 04:03PM [connect]: 	Connected to project "Project28" and design "Full_Chip_Eigenmode" 😀

In [4]:
# Printing Object Names in ansys design
pinfo.get_all_object_names()

['main',
 'sample_holder',
 'prime_cpw_TQ1',
 'second_cpw_TQ1',
 'prime_cpw_TQ0',
 'second_cpw_TQ0',
 'prime_cpw_TQ3',
 'second_cpw_TQ3',
 'trace_cpw_left',
 'trace_cpw_right',
 'b_wire_Q0_bottom',
 'second_cpw_L_brackeb0_bottom',
 'trace_meander_Q0_bottom',
 'trace_bias0_bottom',
 'a_wire_Q0_top',
 'b_wire_Q0_top',
 'second_cpw_L_bracket0_top',
 'trace_bias0_top',
 'a_wire_Q1_top',
 'b_wire_Q1_top',
 'second_cpw_L_bracket1_top',
 'trace_bias1_top',
 'trace_meander_Q0_top',
 'trace_meander_Q1_top',
 'trace_two_qubit_coupler',
 'launch_pad_Transmission_Launch_Pad_L',
 'launch_pad_Transmission_Launch_Pad_R',
 'launch_pad_Qubit_0_Top_Control_Launch_Pad',
 'launch_pad_Qubit_1_Top_Control_Launch_Pad',
 'pad_top_Q0_bottom',
 'b_connector_pad_Q0_bottom',
 'launch_pad_Launch_Pad_0_Bottom',
 'pad_top_Q0_top',
 'a_connector_pad_Q0_top',
 'b_connector_pad_Q0_top',
 'pad_top_Q1_top',
 'a_connector_pad_Q1_top',
 'b_connector_pad_Q1_top',
 'JJ_rect_Lj_Q0_bottom_rect_jj_L',
 'JJ_rect_Lj_Q0_top_rect_jj_L',
 'JJ_rect_Lj_Q1_top_rect_jj_L',
 'ground_main_plane',
 'Rectangle1',
 'Rectangle2',
 'Rectangle3',
 'Rectangle4',
 'Rectangle5',
 'JJ_Lj_Q0_bottom_rect_jj_L_',
 'JJ_Lj_Q0_top_rect_jj_L_',
 'JJ_Lj_Q1_top_rect_jj_L_']

In [5]:
pinfo.design.get_setup_names()

('Setup',)

# Convert 2 JJ to 1 JJ, remember to double Cj. Reduce Lj by half.

In [6]:
# Defining the Junction in pyEPR
pinfo.junctions['j1'] = {'Lj_variable' : 'Q0_bottom_Lj',        # Inductance Variable Name
                         'rect'        : 'JJ_rect_Lj_Q0_bottom_rect_jj_L',  # Name of the rectangle geometry where Lumped RLC is specified
                         'line'        : 'JJ_Lj_Q0_bottom_rect_jj_L_',   # HFSS Polyline that spans the length of the rectangle
                         'length'      : epr.parse_units('0.06mm'),
                         'Cj_variable' : 'Q0_bottom_Cj'}  
pinfo.junctions['j2'] = {'Lj_variable' : 'Q0_top_Lj',        # Inductance Variable Name
                         'rect'        : 'JJ_rect_Lj_Q0_top_rect_jj_L',  # Name of the rectangle geometry where Lumped RLC is specified
                         'line'        : 'JJ_Lj_Q0_top_rect_jj_L_',   # HFSS Polyline that spans the length of the rectangle
                         'length'      : epr.parse_units('0.06mm'),
                         'Cj_variable' : 'Q0_top_Cj'}  

pinfo.junctions['j3'] = {'Lj_variable' : 'Q0_bottom_Lj',        # Inductance Variable Name
                         'rect'        : 'JJ_rect_Lj_Q0_bottom_rect_jj_L',  # Name of the rectangle geometry where Lumped RLC is specified
                         'line'        : 'JJ_Lj_Q0_bottom_rect_jj_L_',   # HFSS Polyline that spans the length of the rectangle
                         'length'      : epr.parse_units('0.06mm'),
                         'Cj_variable' : 'Q0_bottom_Cj'}  
pinfo.validate_junction_info()  # Raises an error if something is wrong with junction definition

In [8]:
# # Simulation Parameters

pinfo.setup.min_pass = 6
pinfo.setup.passes = 15    # Maximum Number of passes
pinfo.setup.n_modes = 9     # Specifying number of modes for eigenmode analysis
pinfo.setup.delta_f = 1
pinfo.setup.min_freq = '1.0GHz'

### Run Eigenmode Simulations

In [ ]:
pinfo.setup.analyze()

INFO 04:06PM [analyze]: Analyzing setup Setup

In [9]:
# pinfo.design.optimetrics.solve_setup(pinfo.design.optimetrics.get_setup_names())

# Eigenmode Analysis

In [10]:
eprh = epr.DistributedAnalysis(pinfo) # epr hfss analysis

Design "Full_Chip_Eigenmode" info:
	# eigenmodes    9
	# variations    1

In [11]:
eprh.get_ansys_frequencies_all()

                Freq. (GHz)  Quality Factor
variation mode
0         0        4.472658    5.777566e+06
          1        4.785402    3.199805e+03
          2        5.397960    9.710957e+06
          3        5.690293    1.026363e+05
          4        6.116033    1.099232e+05
          5        6.802255    8.499586e+03
          6        7.330488    5.762216e+03
          7        7.516350    5.293345e+03
          8       10.338823    1.163410e+03

In [12]:
eprh.hfss_report_full_convergence()

INFO 01:36PM [hfss_report_full_convergence]: Creating report for variation 0
INFO 01:36PM [hfss_report_f_convergence]: Saved convergences to C:\data-pyEPR\Project28\Full_Chip_Eigenmode\hfss_eig_f_convergence.csv

In [13]:
eprh.get_mesh_statistics()

,Unnamed: 0,Num Tets,Min edge length,Max edge length,RMS edge length,Min tet vol,Max tet vol,Mean tet vol,Std Devn (vol)
0,main,208628,0.003167,1.06491,0.088938,7.565720e-10,0.050106,0.000072,0.000723
1,sample_holder,111457,0.003642,1.02912,0.136559,1.710160e-09,0.063266,0.000322,0.002208

# EPR Analysis

In [14]:
my_epr = eprh.do_EPR_analysis()

Variation 0  [1/1]

  Mode 0 at 4.47 GHz   [1/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               98.8%  4.867e-24 6.028e-26

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign s_0j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 98.28%
	j1               1.06048  (+)        0.0185929
		Energy fraction (Lj over Lj&Cj)= 99.05%
	j2              5.51872e-06  (+)        5.29984e-08
		Energy fraction (Lj over Lj&Cj)= 98.28%
	j3               1.06048  (+)        0.0185929
		(U_tot_cap-U_tot_ind)/mean=-34.57%
WARNING: This simulation must not have converged well!!!                The difference in the total cap and ind energies is larger than 10%.                Proceed with caution.

  Mode 1 at 4.79 GHz   [2/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                3.2%  1.511e-23 1.462e-23

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_1j   sign s_1j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 98.03%
	j1              0.000830539  (+)        1.6669e-05
		Energy fraction (Lj over Lj&Cj)= 98.91%
	j2              0.0117571  (+)        0.00012925
		Energy fraction (Lj over Lj&Cj)= 98.03%
	j3              0.000830539  (+)        1.6669e-05
		(U_tot_cap-U_tot_ind)/mean=0.95%

  Mode 2 at 5.40 GHz   [3/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                1.6%  3.606e-24 3.549e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_2j   sign s_2j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 97.51%
	j1              2.27383e-08  (+)        5.80672e-10
		Energy fraction (Lj over Lj&Cj)= 98.62%
	j2              0.00299298  (+)        4.18656e-05
		Energy fraction (Lj over Lj&Cj)= 97.51%
	j3              2.27383e-08  (+)        5.80672e-10
		(U_tot_cap-U_tot_ind)/mean=0.66%

  Mode 3 at 5.69 GHz   [4/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               93.6%  8.377e-24 5.369e-25

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_3j   sign s_3j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 97.24%
	j1              2.41181e-06  (+)        6.84423e-08
		Energy fraction (Lj over Lj&Cj)= 98.47%
	j2              0.00445384  (+)        6.92304e-05
		Energy fraction (Lj over Lj&Cj)= 97.24%
	j3              2.41181e-06  (+)        6.84423e-08
		(U_tot_cap-U_tot_ind)/mean=87.17%
WARNING: This simulation must not have converged well!!!                The difference in the total cap and ind energies is larger than 10%.                Proceed with caution.

  Mode 4 at 6.12 GHz   [5/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               94.7%  3.725e-24 1.961e-25

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_4j   sign s_4j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 96.83%
	j1              5.87056e-07  (+)        1.92456e-08
		Energy fraction (Lj over Lj&Cj)= 98.24%
	j2               1.01586  (+)        0.0182417
		Energy fraction (Lj over Lj&Cj)= 96.83%
	j3              5.87056e-07  (+)        1.92456e-08
		(U_tot_cap-U_tot_ind)/mean=-2.41%

  Mode 5 at 6.80 GHz   [6/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                0.2%  1.697e-24 1.693e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_5j   sign s_5j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 96.10%
	j1              0.00273431  (+)        0.000110883
		Energy fraction (Lj over Lj&Cj)= 97.83%
	j2              9.15622e-09  (+)        2.03383e-10
		Energy fraction (Lj over Lj&Cj)= 96.10%
	j3              0.00273431  (+)        0.000110883
		(U_tot_cap-U_tot_ind)/mean=-0.15%

  Mode 6 at 7.33 GHz   [7/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                0.7%  1.115e-24 1.108e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_6j   sign s_6j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 95.50%
	j1              2.8421e-08  (+)        1.3385e-09
		Energy fraction (Lj over Lj&Cj)= 97.49%
	j2              5.40899e-05  (+)        1.39532e-06
		Energy fraction (Lj over Lj&Cj)= 95.50%
	j3              2.8421e-08  (+)        1.3385e-09
		(U_tot_cap-U_tot_ind)/mean=0.35%

  Mode 7 at 7.52 GHz   [8/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                1.1%  1.655e-24 1.637e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_7j   sign s_7j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 95.28%
	j1              1.65368e-08  (+)        8.18799e-10
		Energy fraction (Lj over Lj&Cj)= 97.36%
	j2              0.0122258  (+)        0.000331577
		Energy fraction (Lj over Lj&Cj)= 95.28%
	j3              1.65368e-08  (+)        8.18799e-10
		(U_tot_cap-U_tot_ind)/mean=-0.05%

  Mode 8 at 10.34 GHz   [9/9]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                0.6%  1.233e-23 1.225e-23

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_8j   sign s_8j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 91.43%
	j1              1.03217e-05  (+)        9.6695e-07
		Energy fraction (Lj over Lj&Cj)= 95.12%
	j2              0.00448161  (+)        0.000229969
		Energy fraction (Lj over Lj&Cj)= 91.43%
	j3              1.03217e-05  (+)        9.6695e-07
		(U_tot_cap-U_tot_ind)/mean=0.10%

ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project28\Full_Chip_Eigenmode\2026-08-03 13-36-45.npz

# Cross Kerr Calculation

In [15]:
epra = epr.QuantumAnalysis(eprh.data_filename)

WARNING 01:38PM [__init__]: <p>Error: <class 'IndexError'></p>

	 Differences in variations:

In [16]:
sol = epra.analyze_all_variations(cos_trunc = None, fock_trunc = 6)

ERROR 01:38PM [_get_participation_normalized]: WARNING: U_tot_cap-U_tot_ind / mean = 174.3% is > 15%.
Is the simulation converged? Proceed with caution
WARNING:py.warnings:C:\Users\012738063\AppData\Local\anaconda3\envs\qmetal3\Lib\site-packages\pyEPR\core_quantum_analysis.py:692: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  result['f_ND'] = pd.Series(f1_ND)*1E-6  # MHz

ERROR 01:38PM [_get_participation_normalized]: WARNING: U_tot_cap-U_tot_ind / mean = 174.3% is > 15%.
Is the simulation converged? Proceed with caution
WARNING:py.warnings:C:\Users\012738063\AppData\Local\anaconda3\envs\qmetal3\Lib\site-packages\pyEPR\core_quantum_analysis.py:711: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  result['Q_coupling'] = self.Qm_coupling[variation][self.Qm_coupling[variation].columns[junctions]][modes]#TODO change the columns to junctions

 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Variation 0

Pm_norm=
modes
0      0.485194
1      1.714690
2      3.202402
3    197.392674
4      0.951763
5      0.728990
6     65.397665
7      0.960467
8      1.229332
dtype: float64

Pm_norm idx =
      j1     j2     j3
0   True  False   True
1  False  False  False
2  False  False  False
3  False  False  False
4  False   True  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False

WARNING:py.warnings:C:\Users\012738063\AppData\Local\anaconda3\envs\qmetal3\Lib\site-packages\pyEPR\core_quantum_analysis.py:716: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  result['Qs'] = self.Qs[variation][self.PM[variation].columns[junctions]][modes] #TODO change the columns to junctions

*** P (participation matrix, not normlz.)
             j1            j2            j3
0  1.022461e+00  5.320856e-06  1.022461e+00
1  8.304037e-04  1.175521e-02  8.304037e-04
2  2.273738e-08  2.992858e-03  2.273738e-08
3  2.411640e-06  4.453528e-03  2.411640e-06
4  5.765390e-07  9.976582e-01  5.765390e-07
5  2.733701e-03  9.154186e-09  2.733701e-03
6  2.842095e-08  5.408979e-05  2.842095e-08
7  1.653128e-08  1.222172e-02  1.653128e-08
8  1.031926e-05  4.480575e-03  1.031926e-05

*** S (sign-bit matrix)
   s_j1  s_j2  s_j3
0     1    -1     1
1     1     1     1
2    -1    -1    -1
3     1     1     1
4     1    -1     1
5     1     1     1
6     1    -1     1
7    -1     1    -1
8    -1     1    -1
*** P (participation matrix, normalized.)
       0.5  5.3e-06      0.5
   0.00083    0.012  0.00083
   2.3e-08    0.003  2.3e-08
   2.4e-06   0.0045  2.4e-06
   5.8e-07     0.95  5.8e-07
    0.0027  9.2e-09   0.0027
   2.8e-08  5.4e-05  2.8e-08
   1.7e-08    0.012  1.7e-08
     1e-05   0.0045    1e-05

*** Chi matrix O1 PT (MHz)
    Diag is anharmonicity, off diag is full cross-Kerr.
      83.6    0.299 1.28e-05  0.00104  0.00155      1.4 1.58e-05 2.97e-05  0.00805
     0.299    0.015  0.00845   0.0133     3.04  0.00251 0.000207   0.0481   0.0242
  1.28e-05  0.00845  0.00121  0.00381    0.872 8.68e-08 5.96e-05   0.0138  0.00696
   0.00104   0.0133  0.00381  0.00299     1.37 8.68e-06 9.34e-05   0.0216   0.0109
   0.00155     3.04    0.872     1.37      157 5.59e-06   0.0214     4.96      2.5
       1.4  0.00251 8.68e-08 8.68e-06 5.59e-06  0.00587 1.32e-07 1.32e-07 6.74e-05
  1.58e-05 0.000207 5.96e-05 9.34e-05   0.0214 1.32e-07 7.31e-07 0.000339 0.000171
  2.97e-05   0.0481   0.0138   0.0216     4.96 1.32e-07 0.000339   0.0392   0.0396
   0.00805   0.0242  0.00696   0.0109      2.5 6.74e-05 0.000171   0.0396  0.00998

*** Chi matrix ND (MHz)

*** Frequencies O1 PT (MHz)
0     4388.222485
1     4783.670508
2     5397.506233
3     5689.580805
4     5952.846190
5     6801.547317
6     7330.476619
7     7513.768993
8    10337.517076
dtype: float64

*** Frequencies ND (MHz)
Series([], dtype: float64)

*** Q_coupling
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
''' After disconnecting, you can close Ansys in the external window '''
pinfo.disconnect()